// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdt6w-qUwg-IPFKgzy-d35e_C5ZgezKVw',
    appId: '1:929231612427:web:050364a87e5cc31e8ff50e',
    messagingSenderId: '929231612427',
    projectId: 'interview-task-project-171f4',
    authDomain: 'interview-task-project-171f4.firebaseapp.com',
    storageBucket: 'interview-task-project-171f4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFlseX7WLlU2siz8olcxRpGmg3FIMCYFs',
    appId: '1:929231612427:android:77add8dd40de4d7f8ff50e',
    messagingSenderId: '929231612427',
    projectId: 'interview-task-project-171f4',
    storageBucket: 'interview-task-project-171f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvqnD_VBalHycDEgKW6yr2zL_t8bUvFtg',
    appId: '1:929231612427:ios:bc84c8aaca7a64a08ff50e',
    messagingSenderId: '929231612427',
    projectId: 'interview-task-project-171f4',
    storageBucket: 'interview-task-project-171f4.appspot.com',
    iosBundleId: 'com.example.interviewTaskProject',
  );
}
